name: "Phpstan"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  phpstan:
    name: "Phpstan"
    uses: contributte/.github/.github/workflows/phpstan.yml@v1

  phpstan24:
    name: "Phpstan"
    uses: contributte/.github/.github/workflows/phpstan.yml@v1
    with:
      php: "8.0"
      makefile: "phpstan24"
      composer: "composer update --prefer-lowest"
